spring.application.name=microscope-control-platform
simulator.base-url=http://localhost:8081


# Expose the prometheus actuator endpoint
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.export.prometheus.enabled=true
